import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Quicksand } from 'next/font/google'

const robotoNormal = Roboto({ style: 'normal', weight: '300', subsets: ['latin'], variable: '--font-roboto-normal'})
const robotoLight = Roboto({ style: 'normal', weight: '100', subsets: ['latin'], variable: '--font-roboto-light'})
const quickSandBold = Quicksand({ style: 'normal', weight: '600', subsets: ['latin'], variable: '--font-quick-bold'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${robotoNormal.variable} font-roboto-normal`}>{children}</body>
    </html>
  )
}
